log:
  level: error
  file: /tmp/mosdns.log

plugins:
  - tag: cache
    type: cache
    args:
      size: 8192
      lazy_cache_ttl: 259200
      dump_file: /etc/mosdns/cache.dump
      dump_interval: 3600

  - tag: local_dns
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: tls://223.5.5.5
        - addr: tls://223.6.6.6

  - tag: remote_dns
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: tls://8.8.4.4
        - addr: tls://208.67.222.222

  - tag: local_sequence
    type: sequence
    args:
      - exec: $local_dns
      - matches: "!resp_ip &/var/mosdns/geoip_cn.txt"
        exec: drop_resp

  - tag: remote_sequence
    type: sequence
    args:
      - matches: qtype 28
        exec: reject 0
      - exec: $remote_dns

  - tag: fallback
    type: fallback
    args:
      primary: local_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  - tag: main
    type: sequence
    args:
      - matches: qtype 65 #28
        exec: reject 0

      - matches: qtype 12
        exec: $local_dns

      - exec: $cache
      - matches: has_resp
        exec: accept

      - matches: qname &/var/mosdns/geosite_cn.txt
        exec: $local_sequence
      - matches: has_resp
        exec: accept

      - matches: qname &/var/mosdns/geosite_geolocation-!cn.txt
        exec: $remote_sequence
      - matches: has_resp
        exec: accept

      - exec: $fallback

  - type: udp_server
    args:
      entry: main
      listen: :5522

api:
  http: :9091
