#!/bin/sh

uci add firewall rule
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].name='Allow-WAN2'
uci add_list firewall.@rule[-1].proto='all'
uci add_list firewall.@rule[-1].src_ip='10.0.0.0/24'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].enabled='1'

uci commit firewall
