#!/bin/sh

# Timezone
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system

# Sysupgrade
chmod +x /etc/config/sysupgrade.sh

# Diagnostics
uci set luci.diag.dns='www.qq.com'
uci set luci.diag.ping='www.qq.com'
uci set luci.diag.route='www.qq.com'
uci commit luci

# DNS
uci set dhcp.@dnsmasq[0].cachesize='0'
uci set dhcp.@dnsmasq[0].min_cache_ttl='0'
uci set dhcp.@dnsmasq[0].noresolv='1'
uci del dhcp.@dnsmasq[0].domain
uci del dhcp.@dnsmasq[0].expandhosts

# DEL DHCP
uci -q del dhcp.wan
uci -q del dhcp.lan

# SET DHCP
uci set dhcp.dhcp='dhcp'
uci set dhcp.dhcp.interface='dhcp'
uci set dhcp.dhcp.start='100'
uci set dhcp.dhcp.limit='150'
uci set dhcp.dhcp.leasetime='12h'
uci set dhcp.dhcp.dhcpv4='server'
uci add_list dhcp.dhcp.dhcp_option='3,10.0.0.1'
uci add_list dhcp.dhcp.dhcp_option='6,10.0.0.7'
uci commit dhcp

# LAN zone
uci add_list firewall.@zone[0].network='dhcp'
uci add_list firewall.@zone[0].network='dhcp6'
uci commit firewall
